-- Add per-decision budget columns to products table
ALTER TABLE products
  ADD COLUMN IF NOT EXISTS budget_supplier INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS budget_collection INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS budget_comm_tiktok INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS budget_comm_press INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS budget_comm_event INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS budget_comm_influencer INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS budget_dist_ecommerce INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS budget_dist_popup INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS budget_dist_multibrand INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS budget_dist_wholesale INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS budget_dist_social_drop INTEGER NOT NULL DEFAULT 0;

NOTIFY pgrst, 'reload schema';
